name: tests-auth
on:
  pull_request:
    paths:
      - 'app/auth/**'
  
jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd app/auth && npm install && npm run test:ci
