apiVersion: skaffold/v2beta4
kind: Config
deploy:
  kubectl:
    manifests:
      - ../k8s/*
build:
  local:
    push: true
  artifacts:
    - image: lahcenedergham/auth
      context: ../app/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: lahcenedergham/client
      context: ../client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
    - image: lahcenedergham/tickets
      context: ../tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: lahcenedergham/orders
      context: ../orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: lahcenedergham/expiration
      context: ../expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: lahcenedergham/payments
      context: ../payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
